###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: esapiens-test-mysql
      working_dir: /application
      volumes:
        - ./application
      environment:
        - MYSQL_ROOT_PASSWORD=abc123
        - MYSQL_DATABASE=commentsapi
        - MYSQL_USER=larauser
        - MYSQL_PASSWORD=larapass
      ports:
        - "3306:3306"

    redis:
      image: redis:alpine
      container_name: esapiens-test-redis

    webserver:
      image: nginx:alpine
      container_name: esapiens-test-webserver
      working_dir: /application
      volumes:
          - ./commentsapi:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"
      links:
        - mysql:esapiens-test-mysql

    php-fpm:
      build: phpdocker/php-fpm
      container_name: esapiens-test-php-fpm
      working_dir: /application
      volumes:
        - ./commentsapi:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      

